### ISSUE TITLE
Error connecting to the Bulb

### ISSUE THREAD

**Issue by lrozi1** [EthemAcar-Dev/OpenYeeLight#1]
When I try to change anything I get an error:
 ![Error](https://i.imgur.com/T9OvcOx.png)

I have LAN Control enabled in the app, did I configure something incorrectly?

Model: Smart LED Bulb 1S (Color)

**Comment by EthemAcar-Dev** [comment]
Is it some kind of firewall/VPN issue?

**Comment by lrozi1** [comment]
I don't have a VPN enabled, and I let the .exe through Windows Defender Firewall. Is that what you mean?

**Comment by EthemAcar-Dev** [comment]
Updated to latest YeelightApi, there is a new Multicast lookup option. I hope that helps you with seeing the device in the software.

**Comment by lrozi1** [comment]
That did! Thank you for the help. Also it works surprisingly well. : )
