### ISSUE TITLE
Decode/encode base64 names

### ISSUE THREAD

**Issue by jordi-7** [EthemAcar-Dev/OpenYeeLight#4]
Hi,
Internally, the bulbs store their name in base64. Your program should be able to send an encoded name and decode it when reading from the bulb.
[
![image](https://user-images.githubusercontent.com/7353995/95731247-8e237380-0c7f-11eb-8fbf-d523f29ed881.png)
](url)

**Comment by EthemAcar-Dev** [comment]
Not sure about this, internally base64 encode happens inside Yeelight API. You can give and take plaintext from it. I don't think you have to encode and decode, the API already does that.

**Comment by jordi-7** [comment]
As stated in the documentation:
![image](https://user-images.githubusercontent.com/7353995/97473838-bbdd0d80-194b-11eb-9e7b-faa3233eac1d.png)

This is what happens when you use special characters in your program and try to get properties from the bulb's memory via telnet:
![image](https://user-images.githubusercontent.com/7353995/97473775-a831a700-194b-11eb-91fb-f5fa75192508.png)

If you encode and decode in base64 you can properly view those special characters. This is from the tool I developed:
![image](https://user-images.githubusercontent.com/7353995/97474177-1d04e100-194c-11eb-9c2b-93ca22eac5be.png)

**Comment by jordi-7** [comment]
Another example:

First I set the character ñ as the name
![image](https://user-images.githubusercontent.com/7353995/97474793-c8159a80-194c-11eb-8d8d-150d2632c970.png)

Then I just hit refresh, nothing else, and your program doesn't know what to do with it
![image](https://user-images.githubusercontent.com/7353995/97474883-e085b500-194c-11eb-87fe-b12967cf81ec.png)

**Comment by EthemAcar-Dev** [comment]
New version with this feature in settings is live.
