### ISSUE TITLE
Lamp not listed

### ISSUE THREAD

**Issue by Zaniyar** [EthemAcar-Dev/OpenYeeLight#8]
I am not able to list my lamp. I am in the same network. Lamp is working with the official Android App. What do I have to do to be able to discover the lamp in the openYeeLight app?

**Comment by EthemAcar-Dev** [comment]
Did you turn on developer mode of the lamp in official Android app?

**Comment by Zaniyar** [comment]
the case is solved: since the new update of the yeelight app on Android, it is not possible to activate the LAN/developer mode anymore - I had to download an older version from 2020. Now its working!
